In [2]:
import numpy as np


In [3]:
 from time import process_time
 

In [5]:
list=[i for i in range (10000)]
start=process_time()
list=[i+5 for i in range(10000)]
end_time=process_time()
print(end_time-start)

0.0018080649999996368


In [9]:
nparr=np.array([i for i in range(10000)])
npst=process_time()
nparr += 5
npend=process_time()
print(npend-npst)

0.0001819290000000251


creating Numpy array

In [10]:
np_arr=np.array([1,2,3,4,5])
print(type(np_arr))
print(np_arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


list as np array

In [12]:
list=[i*i for i in range(5)]
print(list)
list_to_nparr=np.array(list)
print(list_to_nparr)

[0, 1, 4, 9, 16]
[ 0  1  4  9 16]


multi dimensional np arrays have tuples--> for each row and each row as element of list . 

In [14]:
 b=np.array([(1,2,3,4,0),(5,6,7,8,9)])
 print(b)

[[1 2 3 4 0]
 [5 6 7 8 9]]


In [15]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


error in string dtype ... only numerical values supported 


NOTE-default dtype=int

In [16]:
"""c=np.array([(1,2,3,4),(5,6,7,8)],dtype=string)
print(c)"""

NameError: ignored

In [19]:
x=np.zeros((4,5))
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [20]:
x=np.zeros((4,5),dtype=int)
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [21]:
y=np.ones((3,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
z=np.full((2,3),80)
print(z)

[[80 80 80]
 [80 80 80]]


creating identity matrix using numpy.(identity matrix is a square matrix ONLY)

In [23]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


arrays with random values. 

In [24]:
b=np.random.random((3,4))
print(b)

[[0.3608628  0.02443305 0.65498903 0.18094151]
 [0.74407279 0.23310886 0.52291998 0.83556211]
 [0.8834633  0.26596878 0.06467077 0.48845389]]


the values will always be between 0 to 1

In [25]:
import random

In [27]:
c=np.random.randint(10,100,(3,7))
print(c)

[[41 31 24 53 45 28 87]
 [38 36 21 18 92 79 60]
 [19 87 87 99 61 27 90]]


using random module .
first two args-->random module
tuple arg--> order of matrix needed

In [28]:
c=np.random.randint(0,10,(3,3))
print(c)

[[8 5 0]
 [5 7 4]
 [6 2 6]]


array for evenly spaced values

In [29]:
d=np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


in the above eg. we get evenely spaced values between 10 and 30 and 5 values .

In [30]:
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


the above function again gives evenly spaced values but the 3rd arg is step or increament . 

In [32]:
e=np.arange(30,10,-5)
print(e)

[30 25 20 15]


ANALYSING NUMPY ARRAY

In [33]:
arr=np.random.randint(10,90,(3,5))

#array dimension
print(arr.shape)

#no. of dimension
print(arr.ndim)

#no. of elements
print(arr.size)

#checking data type of values in array
print(arr.dtype)



(3, 5)
2
15
int64


MATHEMATICAL OPERATIONS ON NUMPY ARRAY

In [34]:
list1=[1,2,3,4,4,5]
list2=[6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 4, 5, 6, 7, 8, 9, 10]


lists are unioned or joined or concatenated

In [36]:
ar=np.random.randint(0,10,(3,3))
arb=np.random.randint(10,20,(3,3))
print(ar)
print(arb)
print(ar+arb) 

[[6 4 1]
 [8 3 3]
 [5 7 5]]
[[14 13 13]
 [17 13 18]
 [18 14 17]]
[[20 17 14]
 [25 16 21]
 [23 21 22]]


In [37]:
print(ar*arb)

[[ 84  52  13]
 [136  39  54]
 [ 90  98  85]]


In [38]:
print(ar-arb)

[[ -8  -9 -12]
 [ -9 -10 -15]
 [-13  -7 -12]]


In [39]:
print(ar/arb)

[[0.42857143 0.30769231 0.07692308]
 [0.47058824 0.23076923 0.16666667]
 [0.27777778 0.5        0.29411765]]


all these functions will be operating element wise . 


In [41]:
np.add(ar,arb)

array([[20, 17, 14],
       [25, 16, 21],
       [23, 21, 22]])

In [42]:
np.subtract(ar,arb)

array([[ -8,  -9, -12],
       [ -9, -10, -15],
       [-13,  -7, -12]])

In [43]:
np.multiply(ar,arb)

array([[ 84,  52,  13],
       [136,  39,  54],
       [ 90,  98,  85]])

In [44]:
np.divide(ar,arb)

array([[0.42857143, 0.30769231, 0.07692308],
       [0.47058824, 0.23076923, 0.16666667],
       [0.27777778, 0.5       , 0.29411765]])

similar to element wise operations . 

ARRAY MANUPULATION

In [49]:

arr=np.random.randint(0,10,(2,3))
print(arr.shape)
print(arr)

(2, 3)
[[3 7 4]
 [2 8 1]]


In [54]:
t_arr=np.transpose(arr)
print(t_arr)
print(t_arr.shape)

[[3 2]
 [7 8]
 [4 1]]
(3, 2)


In [56]:
t2=arr.T
print(t2)
print(t2.shape)

[[3 2]
 [7 8]
 [4 1]]
(3, 2)


In [57]:
#reshaping the array

a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 1 6]
 [8 4 1]]
(2, 3)


In [58]:
b=a.reshape(3,2)
print(b)

[[4 1]
 [6 8]
 [4 1]]


reshaping is one of the most important func in ML . rehspaing is not same as transpose , it just reshapes . 
