<a href="https://colab.research.google.com/github/Saumya-Sejal/Saumya-Sejal.github.io/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pandas library analysing data and arranging data

dataFrame is 2-d array structure with labelled axes.

In [ ]:
import pandas as pd


creating data frame 





In [ ]:
#import boston from sklearn
from sklearn.datasets import load_boston


In [ ]:
bd=load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [ ]:
print(type(bd))

<class 'sklearn.utils.Bunch'>


In [ ]:
print(bd)

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]]), 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 1

pandas chnages above data to more structured table .

In [ ]:
bostondf=pd.DataFrame(bd.data,columns=bd.feature_names)
#all features included

In [ ]:
bostondf.head() #prints first 5 data of table 

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3  0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4  0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33

[5 rows x 13 columns]

the above data is much more structured with row name and column name than that printed from sklearn library . 


In [ ]:
bostondf.shape

(506, 13)

importing dataset from a csv file. 
CSV is nothing but comma sepearted data set . 

In [ ]:
diabetesdf=pd.read_csv("/content/diabetes.csv")

In [ ]:
print(type(diabetesdf))

<class 'pandas.core.frame.DataFrame'>


In [ ]:
type(bd)

sklearn.utils.Bunch

In [ ]:
type(bostondf)

pandas.core.frame.DataFrame

the above shows the type diff between bd and boston_dataframe .

In [ ]:
diabetesdf.head() 

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [ ]:
diabetesdf.shape

(768, 9)

**including excel file as dataset in pandas **

In [ ]:
eng=pd.read_excel("/content/Untitled form (Responses).xlsx")

In [ ]:
eng.head()

Timestamp  ... Can you please briefly tell us what made you choose what you did in the questions above? What prompted your decisions?
0 2020-11-23 08:58:13.135  ...                                                NaN                                                                    
1 2020-11-23 09:38:15.607  ...                                                NaN                                                                    
2 2020-11-23 11:28:15.374  ...  Sense of responsibility and intend to do somet...                                                                    
3 2020-11-23 11:29:45.395  ...                                                NaN                                                                    
4 2020-11-28 11:51:12.703  ...                                                NaN                                                                    

[5 rows x 18 columns]

In [ ]:
eng.shape

(271, 18)

reverse function of read csv---> loadig Dataframe to a csv file.

In [ ]:
bostondf.to_csv("bostondf.csv")

In [ ]:
bostondf.to_excel("boston.xlsx")

In [ ]:
eng.to_csv("trolley.csv")

creating dataframe with random values

In [ ]:
import numpy as np

In [ ]:
randomtab=np.random.randint(0,10,(20,10))
print(randomtab)
randomdf=pd.DataFrame(randomtab)
randomdf.head()

[[9 2 4 4 8 1 3 4 5 9]
 [6 6 6 3 0 0 4 9 5 2]
 [4 6 3 8 4 9 3 5 7 7]
 [5 1 7 2 5 4 1 9 0 1]
 [7 5 3 7 4 0 5 3 9 9]
 [4 1 6 2 0 7 9 2 0 5]
 [5 4 2 3 2 5 1 7 9 9]
 [9 2 3 1 6 1 3 7 8 3]
 [4 3 6 5 0 2 7 7 6 8]
 [8 9 5 6 3 1 9 5 0 8]
 [0 2 7 2 1 8 2 1 9 8]
 [9 9 7 2 3 3 9 6 2 9]
 [4 3 7 6 2 9 4 7 2 8]
 [4 0 5 3 9 0 9 2 5 6]
 [1 0 1 5 9 5 0 8 9 8]
 [7 6 1 1 6 0 6 6 0 9]
 [2 9 5 7 8 5 4 1 6 3]
 [1 6 3 7 6 5 7 7 8 6]
 [0 8 3 4 4 7 9 3 7 8]
 [0 3 6 7 5 9 7 5 8 6]]


0  1  2  3  4  5  6  7  8  9
0  9  2  4  4  8  1  3  4  5  9
1  6  6  6  3  0  0  4  9  5  2
2  4  6  3  8  4  9  3  5  7  7
3  5  1  7  2  5  4  1  9  0  1
4  7  5  3  7  4  0  5  3  9  9

In [ ]:
rand2=pd.DataFrame(np.random.randint(0,10,(10,20)))
rand2.head()


0   1   2   3   4   5   6   7   8   ...  11  12  13  14  15  16  17  18  19
0   1   9   4   1   2   1   1   9   8  ...   1   3   0   0   3   9   1   1   0
1   1   5   7   4   0   1   5   3   9  ...   9   7   3   9   7   9   2   1   1
2   7   1   0   9   5   4   9   6   8  ...   5   4   4   9   3   6   8   1   7
3   5   8   2   1   5   4   5   0   2  ...   4   7   5   7   3   2   1   9   8
4   6   9   2   4   7   8   4   4   3  ...   2   6   1   4   0   9   1   3   2

[5 rows x 20 columns]

inspecting dataFrame

In [ ]:
eng.tail()

Timestamp  ... Can you please briefly tell us what made you choose what you did in the questions above? What prompted your decisions?
266 2020-12-03 18:50:07.576  ...                                                NaN                                                                    
267 2020-12-03 19:48:40.512  ...                                                NaN                                                                    
268 2020-12-05 21:22:43.222  ...                                                Idk                                                                    
269 2020-12-13 20:02:42.843  ...                                                NaN                                                                    
270 2020-12-14 22:30:33.149  ...                What's best according to situation.                                                                    

[5 rows x 18 columns]

In [ ]:
#tail() prints last 5 rows

In [ ]:
eng.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271 entries, 0 to 270
Data columns (total 18 columns):
 #   Column                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Non-Null Count  Dtype         
---  ------                                                                                                                                                                                                                                              

In [ ]:
bostondf.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
dtypes: float64(13)
memory usage: 51.5 KB


info() gives info abot all the colums and values stored in them 


Finding Null values in Dtaframe 

In [ ]:
bostondf.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
dtype: int64

In [ ]:
diabetesdf.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

in diabetes dataframe outcome=0: not diabetic and outcome=1 diabetic. hence we will count values with certain feild value. 


In [ ]:
diabetesdf.value_counts("Outcome")

Outcome
0    500
1    268
dtype: int64

In [ ]:
eng.value_counts('What is your age?')

What is your age?
18                    81
17                    23
48                    20
49                    17
19                    16
50                    14
47                    12
20                     7
45                     6
14                     6
51                     5
40                     5
15                     5
42                     4
52                     4
46                     4
41                     4
29                     3
16                     3
13                     3
22                     2
35                     2
44                     2
43                     2
57                     2
60                     2
21                     1
12                     1
27                     1
Jaan ke kya karoge     1
30                     1
37                     1
75 yrs.                1
53                     1
54                     1
105                    1
450                    1
13 years               1
17.years               1
18 yrs 

grouping values based on name or values

In [ ]:
diabetesdf.groupby('Outcome').mean()

Pregnancies     Glucose  ...  DiabetesPedigreeFunction        Age
Outcome                           ...                                     
0           3.298000  109.980000  ...                  0.429734  31.190000
1           4.865672  141.257463  ...                  0.550500  37.067164

[2 rows x 8 columns]

# statistical Measures on datframe

In [ ]:
bostondf.count()

CRIM       506
ZN         506
INDUS      506
CHAS       506
NOX        506
RM         506
AGE        506
DIS        506
RAD        506
TAX        506
PTRATIO    506
B          506
LSTAT      506
dtype: int64

column wise mean values

In [ ]:
bostondf.mean()

CRIM         3.613524
ZN          11.363636
INDUS       11.136779
CHAS         0.069170
NOX          0.554695
RM           6.284634
AGE         68.574901
DIS          3.795043
RAD          9.549407
TAX        408.237154
PTRATIO     18.455534
B          356.674032
LSTAT       12.653063
dtype: float64

standard deviation column wise

In [ ]:
diabetesdf.std()

Pregnancies                   3.369578
Glucose                      31.972618
BloodPressure                19.355807
SkinThickness                15.952218
Insulin                     115.244002
BMI                           7.884160
DiabetesPedigreeFunction      0.331329
Age                          11.760232
Outcome                       0.476951
dtype: float64

max and min value of each column 

In [ ]:
diabetesdf.min()


Pregnancies                  0.000
Glucose                      0.000
BloodPressure                0.000
SkinThickness                0.000
Insulin                      0.000
BMI                          0.000
DiabetesPedigreeFunction     0.078
Age                         21.000
Outcome                      0.000
dtype: float64

In [ ]:
diabetesdf.max()

Pregnancies                  17.00
Glucose                     199.00
BloodPressure               122.00
SkinThickness                99.00
Insulin                     846.00
BMI                          67.10
DiabetesPedigreeFunction      2.42
Age                          81.00
Outcome                       1.00
dtype: float64

ALL Statistical measures together column-wise

In [ ]:
diabetesdf.describe()

Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

#Manupulating dataFrame

adding a column to a dataframe

In [ ]:
bostondf['Price']=bd.target

In [ ]:
bostondf.head()

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  Price
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98   24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14   21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03   34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94   33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33   36.2

[5 rows x 14 columns]

removing a row

In [ ]:
bostondf.drop(index=0,axis=0)

CRIM   ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  Price
1    0.02731  0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14   21.6
2    0.02729  0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03   34.7
3    0.03237  0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94   33.4
4    0.06905  0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33   36.2
5    0.02985  0.0   2.18   0.0  0.458  ...  222.0     18.7  394.12   5.21   28.7
..       ...  ...    ...   ...    ...  ...    ...      ...     ...    ...    ...
501  0.06263  0.0  11.93   0.0  0.573  ...  273.0     21.0  391.99   9.67   22.4
502  0.04527  0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   9.08   20.6
503  0.06076  0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   5.64   23.9
504  0.10959  0.0  11.93   0.0  0.573  ...  273.0     21.0  393.45   6.48   22.0
505  0.04741  0.0  11.93   0.0  0.573  ...  273.0     21.0  396.90   7.88   11.9

[505 rows x 14 columns]

drop column

In [ ]:
bos2=bostondf.drop(columns='ZN',axis=1)

locating row using index value

In [ ]:
bostondf.iloc[2]

CRIM         0.02729
ZN           0.00000
INDUS        7.07000
CHAS         0.00000
NOX          0.46900
RM           7.18500
AGE         61.10000
DIS          4.96710
RAD          2.00000
TAX        242.00000
PTRATIO     17.80000
B          392.83000
LSTAT        4.03000
Price       34.70000
Name: 2, dtype: float64

gives all values in in row-2

In [ ]:
bostondf.iloc[0]

CRIM         0.00632
ZN          18.00000
INDUS        2.31000
CHAS         0.00000
NOX          0.53800
RM           6.57500
AGE         65.20000
DIS          4.09000
RAD          1.00000
TAX        296.00000
PTRATIO     15.30000
B          396.90000
LSTAT        4.98000
Price       24.00000
Name: 0, dtype: float64

In [ ]:
bostondf.iloc[:,0] #prints 1st column

0      0.00632
1      0.02731
2      0.02729
3      0.03237
4      0.06905
        ...   
501    0.06263
502    0.04527
503    0.06076
504    0.10959
505    0.04741
Name: CRIM, Length: 506, dtype: float64

In [ ]:
print(bostondf.iloc[:,1]) #2nd column
print(bostondf.iloc[:,-1]) #last column

0      18.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
501     0.0
502     0.0
503     0.0
504     0.0
505     0.0
Name: ZN, Length: 506, dtype: float64
0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: Price, Length: 506, dtype: float64


Correlation 
positive-same direction
negative-different direction

In [ ]:
bostondf.corr()

CRIM        ZN     INDUS  ...         B     LSTAT     Price
CRIM     1.000000 -0.200469  0.406583  ... -0.385064  0.455621 -0.388305
ZN      -0.200469  1.000000 -0.533828  ...  0.175520 -0.412995  0.360445
INDUS    0.406583 -0.533828  1.000000  ... -0.356977  0.603800 -0.483725
CHAS    -0.055892 -0.042697  0.062938  ...  0.048788 -0.053929  0.175260
NOX      0.420972 -0.516604  0.763651  ... -0.380051  0.590879 -0.427321
RM      -0.219247  0.311991 -0.391676  ...  0.128069 -0.613808  0.695360
AGE      0.352734 -0.569537  0.644779  ... -0.273534  0.602339 -0.376955
DIS     -0.379670  0.664408 -0.708027  ...  0.291512 -0.496996  0.249929
RAD      0.625505 -0.311948  0.595129  ... -0.444413  0.488676 -0.381626
TAX      0.582764 -0.314563  0.720760  ... -0.441808  0.543993 -0.468536
PTRATIO  0.289946 -0.391679  0.383248  ... -0.177383  0.374044 -0.507787
B       -0.385064  0.175520 -0.356977  ...  1.000000 -0.366087  0.333461
LSTAT    0.455621 -0.412995  0.603800  ... -0.366087  1.000000 -0.737663
Price   -0.388305  0.360445 -0.483725  ...  0.333461 -0.737663  1.000000

[14 rows x 14 columns]